behaviors:
    CarDrive:
        trainer_type: ppo    
        summary_freq: 10000
        max_steps: 20000000
environment_parameters:
  block_offset:
    curriculum:
      - name: Lesson1  # Follow lane, no obstacle
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 30
        value: 0.0
      - name: Lesson2  # All obstacles on the left side of the road. It will gradually move towards the other end in the following lessons
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 2.0
      - name: Lesson3  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 3.0
      - name: Lesson4  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 4.0
      - name: Lesson5  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 5.0
      - name: Lesson6  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 6.0
      - name: Lesson7  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 7.0
      - name: Lesson8  
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 8.0
      - name: Lesson9
        completion_criteria:
          measure: reward
          behavior: CarDrive
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 50
        value: 9.0
      - name: Lesson10  # Random Obstacle Locations [0, block_offset], different for every obstacle
        value: 10.0